# Generated by Django 3.2.6 on 2021-09-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210909_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'GitHub'), ('google', 'Google')], default='email', max_length=10),
        ),
    ]
